INSERT INTO original_cards (card_name, card_value, quantity, description, is_put_aside)
VALUES ('Hercegnő', 9, 1, 'Ha bármilyen okból kijátszod vagy eldobod ezt a kártyát, kiesel a körből.', false),
       ('Grófnő', 8, 1, 'Ha ez a kártya a Királlyal vagy Herceggel egyszerre van a kezedben, el kell dobnod ezt a lapot.', false),
       ('Király', 7, 1, 'Cserélj kártyát egy általad választott játékossal!', false),
       --> ('Kancellár', 6, 2,  'Húzz két kártyát! A háromból tarts meg egyet, a másik kettőt tedd tetszőleges sorrendben a pakli aljára!', false),
       --> ('Kancellár', 6, 2,  'Húzz két kártyát! A háromból tarts meg egyet, a másik kettőt tedd tetszőleges sorrendben a pakli aljára!', false),
       ('Herceg', 5, 2, 'Válassz egy játékost (akár magadat is)! A játékos dobja el a kezében lévő lapot és húzzon egy újat!', false),
       ('Herceg', 5, 2, 'Válassz egy játékost (akár magadat is)! A játékos dobja el a kezében lévő lapot és húzzon egy újat!', false),
       ('Szobalány', 4, 2, 'A következő körödig a többi játékos kártyáinak hatása nem érvényesül rád.', false),
       ('Szobalány', 4, 2, 'A következő körödig a többi játékos kártyáinak hatása nem érvényesül rád.', false),
       ('Báró', 3, 2, 'Válassz egy játékost és hasonlítsátok össze a kártyáitokat. A kisebb értékű lap tulajdonosa kiesik a körből. (Döntetlennél nem történik semmi).', false),
       ('Báró', 3, 2, 'Válassz egy játékost és hasonlítsátok össze a kártyáitokat. A kisebb értékű lap tulajdonosa kiesik a körből. (Döntetlennél nem történik semmi).', false),
       ('Pap', 2, 2, 'Megnézheted egy másik játékos kézben tartott kártyáját.', false),
       ('Pap', 2, 2, 'Megnézheted egy másik játékos kézben tartott kártyáját.', false),
       ('Őr', 1, 5, 'Válassz egy játékost és nevezz meg egy kártyát (kivéve az Őrt). Ha ez a karakter van a kezében, kiesik a körből.', false),
       ('Őr', 1, 5, 'Válassz egy játékost és nevezz meg egy kártyát (kivéve az Őrt). Ha ez a karakter van a kezében, kiesik a körből.', false),
       ('Őr', 1, 5, 'Válassz egy játékost és nevezz meg egy kártyát (kivéve az Őrt). Ha ez a karakter van a kezében, kiesik a körből.', false),
       ('Őr', 1, 5, 'Válassz egy játékost és nevezz meg egy kártyát (kivéve az Őrt). Ha ez a karakter van a kezében, kiesik a körből.', false),
       ('Őr', 1, 5, 'Válassz egy játékost és nevezz meg egy kártyát (kivéve az Őrt). Ha ez a karakter van a kezében, kiesik a körből.', false);
       --> ('Kém', 0, 2, 'Ha egyedüliként maradsz bent a kör végén, aki Kémet játszott ki vagy dobott el, kapsz 1 szerelmeslevelet.', false),
       --> ('Kém', 0, 2, 'Ha egyedüliként maradsz bent a kör végén, aki Kémet játszott ki vagy dobott el, kapsz 1 szerelmeslevelet.', false);
